name: Terraform Apply on Commit

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure AWS credentials using GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
        env:
          ACTIONS_STEP_DEBUG: true

      # Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # Network Directory Terraform Execution
      - name: Terraform Init in Network Folder
        working-directory: ./Network
        run: terraform init

      - name: Terraform Plan in Network Folder
        working-directory: ./Network
        run: terraform plan

      - name: Terraform Apply in Network Folder
        working-directory: ./Network
        run: terraform apply -auto-approve

      # Webserver Directory Terraform Execution
      - name: Terraform Init in Webserver Folder
        working-directory: ./Webserver
        run: terraform init

      - name: Terraform Plan in Webserver Folder
        working-directory: ./Webserver
        run: terraform plan

      - name: Terraform Apply in Webserver Folder
        working-directory: ./Webserver
        run: terraform apply -auto-approve
